feat!: New version with more defaults

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -1,43 +1,62 @@
 name: Download file from GitHub repository
-description: Download a given file from a GitHub repository using only curl
+description: Composite action that downloads a given file from a GitHub repository
 
 author: "CDQ AG"
 branding:
-  icon: 'shield'
-  color: 'red'
+  icon: 'download'
+  color: 'green'
 
 inputs:
-  organization:
-    description: Name of the organization that owns the repository
-    required: true
-  repository:
-    description: Name of the repository
-    required: true
-  file-path:
-    description: Path to the file in the repository, relative to the repository root
-    required: true
-  target-file:
-    description: Path to the file in the workspace where the downloaded file should be saved
-    required: true
   github-token:
     description: GitHub token with read access to the repository, default GitHub token is used if not provided
+    default: "${{ github.token }}"
+
+  repository:
+    description: Name of the repository. By default, the repository where the action is run
+    default: "${{ github.repository }}"
+
+  file:
+    description: File to download
     required: true
+
+  destination:
+    description: Custom destination path for the downloaded file, defaults (empty string) to the file name
+    default: ""
 
 runs:
   using: 'composite'
   steps:
-    - name: Calculate the download URL
+    - name: Get download URL
+      id: get_download_url
       shell: bash
       env: 
-        FILE_PATH: ${{ inputs.file-path }}
-        TARGET_FILE: ${{ inputs.target-file }}
-        ORGANIZATION: ${{ inputs.organization }}
+        FILE_PATH: ${{ inputs.file }}
         REPOSITORY: ${{ inputs.repository }}
         TOKEN: ${{ inputs.github-token }}
       run: |
-        file_metadata_url="https://api.github.com/repos/$ORGANIZATION/$REPOSITORY/contents/$FILE_PATH"
+        metadata_url="https://api.github.com/repos/${REPOSITORY}/contents/${FILE_PATH}"
+        echo "::debug::File metadata URL: $metadata_url"
 
-        file_download_url=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" $file_metadata_url | jq -r '.download_url')
+        download_url=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" "$metadata_url")
+        
+        download_url=$(echo "$download_url" | jq -r '.download_url')
+        if [ "$download_url" == "null" ]; then
+          echo "::error::Failed to get download URL for file: $FILE_PATH. Got response: $download_url"
+          exit 1
+        fi
 
-        curl -L $file_download_url -o $TARGET_FILE
+        echo "::debug::File download URL: $download_url"
+        echo "download_url=$download_url" >> $GITHUB_OUTPUT
 
+    - name: Download file
+      shell: bash
+      env: 
+        FILE_PATH: ${{ inputs.file }}
+        DESTINATION: ${{ inputs.destination }}
+        DOWNLOAD_URL: ${{ steps.get_download_url.outputs.download_url }}
+      run: |
+        if [ -z "$DESTINATION" ]; then
+          DESTINATION=$(basename "$FILE_PATH")
+        fi
+
+        curl -L "$DOWNLOAD_URL" -o "$DESTINATION"
